---
- hosts: all
  become: true
  vars:
     package: vim
  tasks:
     - name: Install Packages
       yum: name={{ item }} state=latest
       with_items:
          - vim
          - git
          - curl 
